name: "Nette Tester"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test84:
    name: "Nette Tester (8.4)"
    runs-on: "blacksmith-2vcpu-ubuntu-2404"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "8.4"
      - uses: "contributte/.github/.github/actions/setup-composer@master"
      - run: "make test"
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_TEST_LIST: ${{ secrets.MAILCHIMP_TEST_LIST }}

  test83:
    name: "Nette Tester (8.3)"
    runs-on: "blacksmith-2vcpu-ubuntu-2404"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "8.3"
      - uses: "contributte/.github/.github/actions/setup-composer@master"
      - run: "make test"
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_TEST_LIST: ${{ secrets.MAILCHIMP_TEST_LIST }}

  test82:
    name: "Nette Tester (8.2)"
    runs-on: "blacksmith-2vcpu-ubuntu-2404"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "8.2"
      - uses: "contributte/.github/.github/actions/setup-composer@master"
      - run: "make test"
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_TEST_LIST: ${{ secrets.MAILCHIMP_TEST_LIST }}

  testlower:
    name: "Nette Tester (8.2 lowest)"
    runs-on: "blacksmith-2vcpu-ubuntu-2404"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "contributte/.github/.github/actions/setup-php@master"
        with:
          php: "8.2"
      - uses: "contributte/.github/.github/actions/setup-composer@master"
        with:
          command: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
      - run: "make test"
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_TEST_LIST: ${{ secrets.MAILCHIMP_TEST_LIST }}
